### ISSUE TITLE
Compilar ada

### ISSUE THREAD

**Issue by FGasquez** [ulises-jeremias/Facultad-de-Informatica#2]
Che, creo que esto no compila...
Http://github.com/ulises-jeremias/Facultad-de-Informatica/blob/master/Tercer%20A%C3%B1o/Segundo%20Semestre/Programacion%20Concurrente/Resoluciones%20Practicas/Practica%205/ejercicio_1/ada/ejercicio_1.ada

**Comment by lucasdc6** [comment]
Yo quiero ver eso!
